my_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      port: 6543
      user: de_user
      password: postgres
      dbname: de_db
      schema: public
      threads: 4
